create table wildfires (
  id bigint generated by default as identity primary key,
  location text not null,
  latitude double precision not null,
  longitude double precision not null,
  intensity text not null,
  size text not null,
  temperature text not null,
  wind_speed text not null,
  status text not null,
  last_update timestamp with time zone default timezone('utc'::text, now()) not null,
  cause text,
  threat text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create an index for faster location-based queries
create index wildfires_location_idx on wildfires (location);
create index wildfires_coordinates_idx on wildfires (latitude, longitude); 